# Name: Meshank Adhia
## TASK 2: Read data from CSV/Excel File

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
read = pd.read_csv('winequality-red.csv',delimiter=";")

In [2]:
for i in read:
    print(i)

fixed acidity
volatile acidity
citric acid
residual sugar
chlorides
free sulfur dioxide
total sulfur dioxide
density
pH
sulphates
alcohol
quality

In [3]:
read.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [4]:
read.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [5]:
x=read[["fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol"]]
y=read[['quality']]

In [6]:
x.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4

In [7]:
y.head()

   quality
0        5
1        5
2        5
3        6
4        5

In [8]:
print(x.shape)
print(y.shape)

(1599, 11)
(1599, 1)

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score,plot_confusion_matrix,accuracy_score
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.1,random_state = 0)
print('xtrain.shape :- ',xtrain.shape)
print('xtest.shape :- ',xtest.shape)
print('ytrain.shape :- ',ytrain.shape)
print('xtest.shape :- ',ytest.shape)
model = MLPClassifier((5,500),max_iter=300)
model.fit(xtrain,ytrain)
ypredict = model.predict(xtest)
print(ypredict)
from sklearn.metrics import confusion_matrix,plot_confusion_matrix
print(confusion_matrix(ypredict,ytest))
print(accuracy_score(ypredict,ytest))

xtrain.shape :-  (1439, 11)
xtest.shape :-  (160, 11)
ytrain.shape :-  (1439, 1)
xtest.shape :-  (160, 1)
[6 5 7 5 6 6 5 6 5 5 5 5 6 5 6 6 7 6 6 5 6 5 6 5 6 5 5 6 5 6 6 6 6 5 6 6 5
 6 6 6 6 6 6 7 6 5 6 6 6 6 5 5 6 6 6 5 5 5 7 5 5 6 6 6 5 6 6 6 6 6 5 6 5 5
 6 6 5 5 5 6 5 5 6 6 6 5 6 5 5 5 5 5 6 5 6 5 6 5 5 6 7 6 6 6 6 5 6 5 6 5 6
 5 6 5 6 6 5 7 6 6 5 6 6 5 6 6 5 5 6 7 5 5 6 6 6 5 6 6 6 5 6 5 6 5 6 6 6 7
 6 5 6 6 5 5 6 6 5 5 6 6]
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 1  4 45 14  0  0]
 [ 0  2 19 55 11  1]
 [ 0  0  0  4  3  1]
 [ 0  0  0  0  0  0]]
0.64375

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state = 0)
print('xtrain.shape :- ',xtrain.shape)
print('xtest.shape :- ',xtest.shape)
print('ytrain.shape :- ',ytrain.shape)
print('xtest.shape :- ',ytest.shape)
model = MLPClassifier((5,500),max_iter=300)
model.fit(xtrain,ytrain)
ypredict = model.predict(xtest)
print(ypredict)
from sklearn.metrics import confusion_matrix,plot_confusion_matrix
print(confusion_matrix(ypredict,ytest))
print(accuracy_score(ypredict,ytest))

xtrain.shape :-  (1279, 11)
xtest.shape :-  (320, 11)
ytrain.shape :-  (1279, 1)
xtest.shape :-  (320, 1)
[6 5 7 5 6 5 5 6 5 5 5 6 6 5 6 6 7 6 6 5 6 6 6 6 6 5 5 6 5 6 6 6 6 5 6 6 5
 5 6 6 6 6 6 7 6 5 5 6 5 6 5 5 6 7 6 5 5 5 7 5 5 6 6 6 5 6 6 6 6 6 5 5 5 5
 6 6 5 5 5 6 6 5 6 6 6 5 6 5 5 5 5 5 5 5 6 5 6 6 5 6 7 6 6 6 6 5 6 5 6 5 6
 5 6 5 5 6 5 7 6 6 5 6 6 5 6 6 5 5 6 7 5 5 6 6 6 5 6 5 6 5 6 5 5 5 5 6 6 6
 6 5 6 6 5 5 5 6 6 5 6 6 6 6 6 5 6 5 6 7 6 5 6 5 5 6 6 6 7 7 6 5 5 7 6 6 7
 5 6 6 5 6 6 6 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 6 6 5 6 5 5 6 5 5 6 6 6 5 5 6
 6 6 5 6 6 6 5 5 5 6 5 6 7 6 6 6 6 6 5 5 5 5 6 5 5 5 5 6 5 5 5 6 6 5 5 5 5
 6 6 7 5 5 5 5 5 5 5 6 6 5 6 6 6 6 7 5 7 7 6 6 5 6 5 5 5 5 6 6 6 5 6 5 5 6
 5 6 5 5 6 5 6 6 7 6 5 5 5 5 6 6 5 6 5 7 6 6 5 7]
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 1  8 95 42  1  0]
 [ 1  3 40 88 18  2]
 [ 0  0  0 12  8  1]
 [ 0  0  0  0  0  0]]
0.596875

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state = 0)
print('xtrain.shape :- ',xtrain.shape)
print('xtest.shape :- ',xtest.shape)
print('ytrain.shape :- ',ytrain.shape)
print('xtest.shape :- ',ytest.shape)
model = MLPClassifier((5,500),max_iter=300)
model.fit(xtrain,ytrain)
ypredict = model.predict(xtest)
print(ypredict)
from sklearn.metrics import confusion_matrix,plot_confusion_matrix
print(confusion_matrix(ypredict,ytest))
print(accuracy_score(ypredict,ytest))

xtrain.shape :-  (1119, 11)
xtest.shape :-  (480, 11)
ytrain.shape :-  (1119, 1)
xtest.shape :-  (480, 1)
[6 5 6 5 5 5 5 6 5 5 5 6 6 5 6 6 7 6 6 5 6 6 6 5 5 5 5 6 5 6 6 6 5 5 6 6 5
 5 6 6 5 7 6 7 6 5 5 5 5 6 5 5 6 7 6 5 5 5 7 6 5 6 6 6 5 6 6 6 6 6 5 6 5 5
 5 6 5 5 5 6 6 5 6 6 6 6 5 5 5 5 5 5 6 5 6 5 6 5 6 6 7 6 6 6 5 6 5 5 6 5 6
 5 6 5 5 6 5 7 7 6 5 6 6 5 5 6 5 5 6 6 5 5 6 5 6 5 6 5 6 5 6 5 5 5 5 5 6 7
 6 5 6 6 5 5 5 6 5 5 6 6 6 5 6 5 6 5 5 6 6 6 6 5 5 7 5 6 5 7 7 5 5 6 6 6 7
 5 6 6 5 6 6 5 6 6 5 5 5 5 5 5 5 6 5 5 5 5 5 6 6 5 6 5 5 7 5 5 6 6 6 5 5 6
 6 6 5 6 6 6 5 5 5 6 5 6 7 6 6 6 7 6 5 5 5 5 6 5 6 5 5 6 5 6 5 6 6 5 5 5 5
 6 6 6 6 5 5 5 5 5 6 5 6 5 6 5 6 6 6 5 7 7 6 6 5 6 6 5 5 5 6 6 6 5 5 5 5 6
 5 5 5 5 6 5 6 6 7 5 5 5 5 6 5 6 5 5 5 7 6 7 5 7 6 6 6 5 6 5 6 5 5 5 7 5 5
 6 5 5 6 6 5 5 5 5 6 6 6 5 5 5 5 7 6 6 5 6 6 6 6 6 6 6 5 6 5 6 5 6 5 6 5 5
 6 5 5 6 6 5 6 6 6 6 6 6 5 6 5 6 6 6 5 5 6 5 5 6 5 6 6 5 6 5 5 5 5 5 5 5 5
 6 6 7 5 5 5 6 6 5 6 5 5 6 6 6 6 6 5 6 5 6 5 5 6 5 5 6 5 6 5 6 6 6 5 5 6 5
 6 5 6 7 5 5 6 5 5 6 6 5 5 5 5 6 5 7 5 5 5 5 7 5 6 5 5 5 5 5 6 6 5 5 6 5]
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  3  13 149  72   4   1]
 [  0   2  57 120  29   2]
 [  0   0   2  12  12   2]
 [  0   0   0   0   0   0]]
0.5854166666666667

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.4,random_state = 0)
print('xtrain.shape :- ',xtrain.shape)
print('xtest.shape :- ',xtest.shape)
print('ytrain.shape :- ',ytrain.shape)
print('xtest.shape :- ',ytest.shape)
model = MLPClassifier((5,500),max_iter=300)
model.fit(xtrain,ytrain)
ypredict = model.predict(xtest)
print(ypredict)
from sklearn.metrics import confusion_matrix,plot_confusion_matrix
print(confusion_matrix(ypredict,ytest))
print(accuracy_score(ypredict,ytest))

xtrain.shape :-  (959, 11)
xtest.shape :-  (640, 11)
ytrain.shape :-  (959, 1)
xtest.shape :-  (640, 1)
[5 6 6 6 7 5 6 6 6 5 6 6 6 5 6 5 7 6 6 6 6 6 6 5 5 5 5 6 5 5 6 5 6 5 6 6 5
 6 6 6 5 6 5 6 6 5 6 5 5 5 6 5 6 6 6 5 5 6 6 6 6 6 6 6 5 6 6 6 6 6 5 5 6 5
 5 6 6 5 5 6 5 5 6 6 6 6 5 6 5 5 5 5 6 6 7 5 6 6 6 6 7 6 5 5 6 6 6 6 6 5 6
 5 6 5 6 5 6 7 6 6 5 6 5 5 5 6 5 5 6 6 5 6 6 7 6 5 6 5 6 6 6 5 6 6 6 6 6 7
 6 6 5 6 6 6 6 6 5 6 6 6 6 6 6 5 6 6 6 6 5 6 5 5 6 6 7 5 7 6 6 5 5 6 6 6 6
 5 6 5 5 5 6 5 6 6 5 5 6 6 6 5 5 6 5 6 5 5 5 6 6 5 5 5 5 5 6 6 6 6 6 5 6 6
 6 5 6 5 6 6 6 6 5 6 6 5 7 6 6 6 7 6 6 5 6 6 6 5 5 5 5 5 5 6 5 6 6 5 5 6 5
 6 6 5 5 6 6 6 6 5 6 5 6 5 6 5 6 6 6 5 6 6 6 6 5 6 6 5 6 6 6 5 5 6 6 6 5 6
 5 5 5 5 6 6 6 5 6 6 6 6 5 6 5 6 5 6 5 6 7 6 6 7 6 6 6 5 6 5 6 5 5 5 7 6 5
 5 6 5 5 6 5 6 5 5 6 6 6 6 6 5 6 6 5 6 5 7 6 6 6 6 5 6 5 5 6 6 5 6 6 6 5 6
 5 6 6 6 6 5 6 6 6 6 6 6 5 6 6 6 6 6 5 5 6 5 5 5 5 6 6 5 6 5 5 5 6 6 5 6 6
 6 6 6 6 5 5 6 6 5 6 5 5 6 6 6 6 6 5 6 7 6 5 5 5 5 5 5 6 6 6 6 6 6 5 6 6 5
 6 5 6 6 5 6 5 5 5 5 6 5 6 5 6 6 6 6 6 5 5 5 6 6 6 5 5 6 6 5 5 6 5 5 6 5 5
 5 6 6 5 6 5 6 6 5 5 6 5 6 6 6 6 5 6 6 6 5 5 6 5 6 5 6 5 6 6 6 5 5 7 6 6 5
 5 5 6 5 6 5 5 5 6 6 6 6 6 5 6 6 6 6 5 6 6 6 6 6 5 6 6 5 6 6 6 5 6 6 6 6 5
 6 6 6 5 5 6 5 6 5 6 6 6 6 6 5 6 5 5 7 5 6 6 6 5 5 6 6 5 6 5 6 6 5 5 6 6 5
 6 6 6 6 6 6 5 6 6 6 6 6 7 6 6 6 5 6 6 5 6 5 5 6 5 5 5 5 6 5 5 6 6 6 5 5 5
 5 6 5 7 6 6 7 6 5 6 6]
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  2   5 148  80   8   1]
 [  2  16 128 180  45   4]
 [  0   2   3   8   7   1]
 [  0   0   0   0   0   0]]
0.5234375

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.5,random_state = 0)
print('xtrain.shape :- ',xtrain.shape)
print('xtest.shape :- ',xtest.shape)
print('ytrain.shape :- ',ytrain.shape)
print('xtest.shape :- ',ytest.shape)
model = MLPClassifier((5,500),max_iter=300)
model.fit(xtrain,ytrain)
ypredict = model.predict(xtest)
print(ypredict)
from sklearn.metrics import confusion_matrix,plot_confusion_matrix
print(confusion_matrix(ypredict,ytest))
print(accuracy_score(ypredict,ytest))

xtrain.shape :-  (799, 11)
xtest.shape :-  (800, 11)
ytrain.shape :-  (799, 1)
xtest.shape :-  (800, 1)
[6 5 7 6 6 5 5 6 5 5 5 6 6 5 6 7 7 6 6 6 7 6 6 6 6 5 5 7 5 6 6 6 6 5 6 6 5
 5 6 6 5 7 6 7 6 5 5 5 5 6 5 5 7 6 6 5 5 6 7 5 5 6 6 6 5 6 6 6 6 7 5 5 5 5
 5 6 5 5 5 6 6 5 6 6 6 5 5 6 5 5 5 5 6 5 7 5 6 6 5 6 7 6 6 6 5 5 5 5 6 5 6
 5 6 5 5 6 5 7 7 6 5 7 6 5 5 6 5 5 6 7 5 5 6 5 6 5 6 5 6 6 7 5 5 5 5 6 6 7
 6 5 6 7 5 5 5 6 5 5 6 6 6 6 6 5 6 5 6 6 6 6 6 5 5 7 7 6 5 7 6 5 5 7 6 7 7
 5 6 6 5 6 6 6 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 7 6 5 5 5 5 6 5 5 6 6 6 5 5 6
 7 5 5 6 6 6 5 5 5 6 5 6 7 6 6 7 6 7 5 5 5 5 5 5 5 5 5 6 5 6 5 6 6 5 5 5 5
 6 6 6 5 5 5 5 5 5 5 5 6 5 6 5 6 6 7 5 7 7 6 7 5 6 5 5 5 5 6 6 6 5 6 6 5 6
 5 6 5 5 6 5 6 6 7 6 5 5 5 6 5 6 5 6 5 7 6 7 5 6 6 6 6 5 7 5 7 5 5 5 7 6 5
 6 5 5 6 6 5 6 5 5 6 6 6 6 5 5 5 6 6 6 5 6 6 5 6 6 6 7 5 6 6 7 5 5 5 7 5 5
 5 6 6 6 5 5 7 6 6 5 6 6 5 6 5 5 7 5 6 5 6 5 5 7 5 6 6 5 6 5 5 5 5 6 5 6 6
 6 5 7 5 5 5 5 6 5 6 5 5 7 6 6 6 6 5 6 7 7 5 5 5 6 5 6 5 7 5 6 6 5 6 5 7 5
 6 5 6 7 5 5 6 5 5 6 6 5 6 5 6 5 5 7 6 5 5 5 7 5 5 5 6 5 5 5 6 5 5 5 5 5 5
 5 6 6 5 6 5 5 5 5 5 5 5 6 6 6 6 5 6 5 7 5 5 6 5 6 5 5 6 5 7 6 5 5 6 5 6 5
 5 5 6 5 6 5 5 5 6 5 6 6 6 5 6 6 5 5 5 7 6 6 6 6 5 6 6 6 6 6 7 6 6 6 5 5 5
 5 6 7 6 5 6 6 6 5 5 6 5 7 6 5 6 5 5 5 6 7 6 6 5 6 6 6 6 7 5 5 5 5 6 7 6 5
 6 5 6 6 6 6 5 6 6 5 7 5 7 5 6 6 5 6 5 5 5 5 6 6 5 5 5 5 6 5 6 6 5 6 5 5 5
 5 6 5 5 6 5 7 5 5 5 5 5 5 6 6 6 5 5 6 5 7 6 6 6 7 5 5 5 5 6 5 5 5 7 5 7 5
 5 6 5 6 5 5 5 5 5 5 5 6 6 6 6 7 7 6 5 5 6 6 7 6 6 5 6 5 7 5 6 5 6 5 7 5 5
 5 5 6 6 5 5 5 6 6 6 6 7 6 6 5 6 5 5 5 6 6 6 6 5 7 5 5 5 6 5 5 6 6 6 6 6 6
 5 6 5 5 5 7 6 5 6 5 5 5 5 7 6 6 5 5 7 6 5 7 6 5 5 6 5 5 5 6 7 5 5 6 5 5 5
 5 5 5 5 5 6 6 5 5 6 5 5 5 6 6 5 6 6 6 5 5 6 6]
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  5  17 238 123  11   1]
 [  0   8  99 175  36   4]
 [  0   1   8  35  35   4]
 [  0   0   0   0   0   0]]
0.56